name: Check BTC Price

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:  # This allows manual triggering

jobs:
  check-price:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger BTC price check
      run: |
        echo "Sending request to ${{ secrets.NETLIFY_URL }}"
        response=$(curl -s -X POST ${{ secrets.NETLIFY_URL }} \
          -H "Content-Type: application/json" \
          -d '{"trigger":"github_action"}')
        echo "Response: $response"
        
        if [[ -z "$response" ]]; then
          echo "Error: No response received"
          exit 1
        elif [[ "$response" == *"Price check triggered by GitHub Actions"* ]]; then
          echo "Price check successfully triggered"
        else
          echo "Unexpected response"
          exit 1
        fi
      env:
        NETLIFY_URL: ${{ secrets.NETLIFY_URL }}