name: Check Bot Health

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # This allows manual triggering

jobs:
  check-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Ping bot
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.NETLIFY_URL }})
        if [[ $response == "200" ]]; then
          echo "Bot is responsive"
        else
          echo "Bot returned unexpected status code: $response"
          exit 1
        fi
      env:
        NETLIFY_URL: ${{ secrets.NETLIFY_URL }}