name: Check BTC Price

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:  # This allows manual triggering

jobs:
  check-price:
    runs-on: ubuntu-latest
    steps:
    - name: Curl request and check response
      run: |
        echo "Sending request to ${{ secrets.NETLIFY_URL }}"
        response=$(curl -v -X POST ${{ secrets.NETLIFY_URL }} -H "Content-Type: application/json" -d '{"message":{"text":"/price"}}')
        echo "Response: $response"
        echo "Response length: ${#response}"
        curl_exit_code=$?
        echo "cURL exit code: $curl_exit_code"
        
        if [[ -z "$response" ]]; then
          echo "Error: No response received"
          exit 1
        else
          echo "Response received successfully"
        fi
      env:
        NETLIFY_URL: ${{ secrets.NETLIFY_URL }}